services:

  ldap:
    image: osixia/openldap:1.5.0
    container_name: ldap
    environment:
      LDAP_ORGANISATION: "sherpout"
      LDAP_DOMAIN: "sherpout.com"
      LDAP_ADMIN_USERNAME: "admin"
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_BASE_DN: "dc=sherpout,dc=com"
      LDAP_TLS: "false"
      LDAP_LOG_LEVEL: "256"
    ports:
      - "389:389"
    command: --copy-service
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap
      - ./ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom

  ldap-admin:
    image: osixia/phpldapadmin:latest
    container_name: ldap-admin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ldap
      PHPLDAPADMIN_HTTPS: false
    ports:
      - "8081:80"
    depends_on:
      - ldap

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: dev-mem
    ports:
      - "8082:8080"
    depends_on:
      - ldap
    command: start-dev

volumes:
  ldap_data:
  ldap_config:

networks:
  default:
    external: true
    name: sherpout