services:

  ldap:
    image: osixia/openldap:1.5.0
    container_name: ldap
    environment:
      LDAP_ORGANISATION: "sherpout"
      LDAP_DOMAIN: "sherpout.com"
      LDAP_ADMIN_USERNAME: "admin"
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_BASE_DN: "dc=sherpout,dc=com"
      LDAP_TLS: "false"
    ports:
      - "389:389"
    command: --copy-service
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap
      - ./ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom

  ldap-admin:
    image: osixia/phpldapadmin:latest
    container_name: ldap-admin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ldap
      PHPLDAPADMIN_HTTPS: false
    ports:
      - "8081:80"
    depends_on:
      - ldap

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: dev-mem
    ports:
      - "8082:8080"
    depends_on:
      - ldap
    command: -v start-dev --import-realm
    volumes:
      - ./keycloak:/opt/keycloak/data/import


  postgres:
    image: 'postgres:latest'
    container_name: psql
    environment:
      - 'POSTGRES_DB=sherpout'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=dev'
    ports:
      - '5435:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql


  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/base.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    restart: unless-stopped

volumes:
  ldap_data:
  ldap_config:
  postgres-data:
    driver: local

networks:
  default:
    external: true
    name: sherpout