services:

  ldap:
    image: osixia/openldap:1.5.0
    container_name: ldap
    environment:
      LDAP_ORGANISATION: "sherpout"
      LDAP_DOMAIN: "sherpout.com"
      LDAP_ADMIN_USERNAME: "admin"
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_BASE_DN: "dc=sherpout,dc=com"
    ports:
      - "389:389"
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap

  ldap-admin:
    image: osixia/phpldapadmin:latest
    container_name: ldap-admin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ldap
      PHPLDAPADMIN_HTTPS: false
    ports:
      - "8081:80"
    depends_on:
      - ldap

  postgres:
    image: 'postgres:latest'
    container_name: sherpout-db
    environment:
      - 'POSTGRES_DB=sherpout'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=dev'
    ports:
      - '5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  ldap_data:
  ldap_config:
  postgres-data:
    driver: local

#networks:
#  default:
#    external: true
#    name: sherpout