server:
  port: 9090
  servlet:
    context-path: /api

minio:
  url: http://localhost:9000
  access:
    name: Xjbrg8rZVQpSWzjtRQI7
    secret: GC5HjRA6xRMK7abijPZXna8LYY5IyZsB7tSv55jL
  bucket:
    name: sherpout

spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/sherpout
    username: dev
    password: secret
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    clean-disabled: false

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost/realms/Sherpout/protocol/openid-connect/certs
          issuers: http://192.168.56.1:8082/realms/Sherpout, http://localhost:8082/realms/Sherpout