server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sherpout
    username: dev
    password: secret
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/Sherpout
          jwk-set-uri: http://localhost:8082/realms/Sherpout/protocol/openid-connect/certs