name: AWS signIn test

on:
  push:
  pull_request:

permissions:
    contents: read
    id-token: write

jobs:
  build:
     runs-on: ubuntu-latest
     steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v6.0.0
          with:
            role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
            aws-region: us-east-1

        - name: Test AWS signIn
          run: |
            aws sts get-caller-identity